/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.UsuarioDAO;
import Model.UsuarioTableModel;
import Objetos.Usuario;
import java.awt.Cursor;
import java.awt.Font;
import java.net.URL;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author michel.matos
 */
public final class JanelaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JanelaUsuario
     */
    
    TelaInicial inicio;
    
    UsuarioTableModel model = new UsuarioTableModel();
    
    public JanelaUsuario() throws ParseException, ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        tabelaUsuario.setModel(model);
        
        organizarCaixasInserir();
        botaoInativar.setVisible(false);
        consultaItens.setVisible(false);
        
        formatar();
    }
    
    public JanelaUsuario(TelaInicial inicio) throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        tabelaUsuario.setModel(model);
        
        organizarCaixasInserir();
        botaoInativar.setVisible(false);
        consultaItens.setVisible(false);
        
        formatar();
        this.inicio = inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caixaUsuario = new javax.swing.JLabel();
        caixaSenhaUsuario = new javax.swing.JLabel();
        caixaInsSenha = new javax.swing.JTextField();
        caixaSenhaUsuario1 = new javax.swing.JLabel();
        caixaTipo = new javax.swing.JLabel();
        caixaCPF1 = new javax.swing.JLabel();
        caixaCargo = new javax.swing.JLabel();
        caixaInsNome = new javax.swing.JTextField();
        caixaInsCargo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        botaoCadastrar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoInativar = new javax.swing.JButton();
        botaoLimpar1 = new javax.swing.JButton();
        caixaPesquisar = new javax.swing.JLabel();
        caixaInsPesquisar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        caixaInsCpf = new javax.swing.JFormattedTextField();
        consultaItens = new javax.swing.JPanel();
        consultaUsuario = new javax.swing.JLabel();
        caixaConsultaSenha = new javax.swing.JLabel();
        consultaCod = new javax.swing.JLabel();
        caixaConsultaTipo = new javax.swing.JLabel();
        consultaTipo = new javax.swing.JLabel();
        caixaConsultaCargo = new javax.swing.JLabel();
        consultaCargo = new javax.swing.JLabel();
        caixaConsultaCod = new javax.swing.JLabel();
        consultaSenha = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        caixaUsuario.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        caixaUsuario.setText("USUÁRIO");

        caixaSenhaUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaSenhaUsuario.setText("Senha");

        caixaInsSenha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        caixaSenhaUsuario1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaSenhaUsuario1.setText("Nome");

        caixaTipo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaTipo.setText("Tipo");

        caixaCPF1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCPF1.setText("CPF");

        caixaCargo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCargo.setText("Cargo");

        caixaInsNome.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        caixaInsCargo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tabelaUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaUsuario);

        botaoCadastrar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Adicionar.png"))); // NOI18N
        botaoCadastrar.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoCadastrar.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoCadastrar.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoAlterar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Alterar.png"))); // NOI18N
        botaoAlterar.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoAlterar.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoAlterar.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoInativar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInativarActionPerformed(evt);
            }
        });

        botaoLimpar1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Limpar.png"))); // NOI18N
        botaoLimpar1.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoLimpar1.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoLimpar1.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpar1ActionPerformed(evt);
            }
        });

        caixaPesquisar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaPesquisar.setText("Pesquisar");

        caixaInsPesquisar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaInsPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caixaInsPesquisarKeyReleased(evt);
            }
        });

        caixaInsCpf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        consultaItens.setBackground(new java.awt.Color(255, 255, 255));
        consultaItens.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 46, 138), 4, true));

        consultaUsuario.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        consultaUsuario.setText("CONSULTA USUÁRIO");

        caixaConsultaSenha.setBackground(new java.awt.Color(0, 0, 0));
        caixaConsultaSenha.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaSenha.setText("Senha");

        consultaCod.setBackground(new java.awt.Color(0, 0, 0));
        consultaCod.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaCod.setText("Código");

        caixaConsultaTipo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaTipo.setText("Tipo");

        consultaTipo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaTipo.setText("Tipo");

        caixaConsultaCargo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaCargo.setText("Cargo");

        consultaCargo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaCargo.setText("Cargo");

        caixaConsultaCod.setBackground(new java.awt.Color(0, 0, 0));
        caixaConsultaCod.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaCod.setText("Código");

        consultaSenha.setBackground(new java.awt.Color(0, 0, 0));
        consultaSenha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaSenha.setText("Senha");

        javax.swing.GroupLayout consultaItensLayout = new javax.swing.GroupLayout(consultaItens);
        consultaItens.setLayout(consultaItensLayout);
        consultaItensLayout.setHorizontalGroup(
            consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaItensLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultaUsuario)
                    .addGroup(consultaItensLayout.createSequentialGroup()
                        .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaConsultaTipo)
                            .addComponent(caixaConsultaCod)
                            .addComponent(caixaConsultaSenha))
                        .addGap(18, 18, 18)
                        .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultaSenha)
                            .addComponent(consultaCod)
                            .addComponent(consultaTipo)
                            .addComponent(consultaCargo)))
                    .addComponent(caixaConsultaCargo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaItensLayout.setVerticalGroup(
            consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaItensLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(consultaUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaCod)
                    .addComponent(consultaCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaSenha)
                    .addComponent(consultaSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaTipo)
                    .addComponent(consultaTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaCargo)
                    .addComponent(consultaCargo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Voltar.png"))); // NOI18N
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseExited(evt);
            }
        });

        tipoComboBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comum", "Administrador" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 661, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(239, 239, 239))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoVoltar)
                                    .addComponent(caixaTipo)
                                    .addComponent(caixaCPF1)
                                    .addComponent(caixaCargo)
                                    .addComponent(caixaSenhaUsuario, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(caixaUsuario)
                                    .addComponent(caixaInsSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(caixaInsCpf)
                                    .addComponent(caixaInsCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(botaoInativar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(caixaSenhaUsuario1)
                                .addGap(18, 18, 18)
                                .addComponent(caixaInsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(consultaItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(caixaPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixaInsPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixaUsuario))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaSenhaUsuario1)
                            .addComponent(caixaInsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaSenhaUsuario))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaCPF1)
                            .addComponent(caixaInsCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaTipo)
                            .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaCargo)
                            .addComponent(caixaInsCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botaoLimpar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoInativar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(consultaItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaInsPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixaPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here:
        Usuario u = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();
        
        try {
            u.setSenhausuario(caixaInsSenha.getText());
            u.setNomecompleto(caixaInsNome.getText());
            u.setCpf(caixaInsCpf.getText());
            u.setTipousuario(tipoUser());
            u.setCargo(caixaInsCargo.getText());
            
            dao.criar(u);
            model.recarregaTabela();
            limpacampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Falha em cadastrar usuário (684987654): " + e);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        model.recarregaTabela();
    }//GEN-LAST:event_formWindowActivated

    public void formatar(){
        JTableHeader tituloTabela = tabelaUsuario.getTableHeader();
        tituloTabela.setFont(new Font("century gothic", Font.BOLD, 12));
        
        DefaultTableCellRenderer centralizar = (DefaultTableCellRenderer)
                tituloTabela.getDefaultRenderer();
        centralizar.setHorizontalAlignment(JLabel.CENTER);
        centralizar.setVerticalAlignment(JLabel.CENTER);
    }
    
    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        // TODO add your handling code here:
        if (tabelaUsuario.getSelectedRow() != -1) {
            model.setValueAt(caixaInsSenha.getText(), tabelaUsuario.getSelectedRow(), 1);
            model.setValueAt(caixaInsNome.getText(), tabelaUsuario.getSelectedRow(), 2);
            model.setValueAt(caixaInsCpf.getText(), tabelaUsuario.getSelectedRow(), 3);
            model.setValueAt(tipoUser(), tabelaUsuario.getSelectedRow(), 4);
            model.setValueAt(caixaInsCargo.getText(), tabelaUsuario.getSelectedRow(), 6);
            
            Usuario u = model.pegaDadosLinha(tabelaUsuario.getSelectedRow());
            UsuarioDAO dao = new UsuarioDAO();
            
            dao.atualizar(u);
            model.recarregaTabela();
            limpacampos();
        }
    }//GEN-LAST:event_botaoAlterarActionPerformed

    public int tipoUser(){
        int tipoUser = 0;
      
        switch (tipoComboBox.getItemAt(tipoComboBox.getSelectedIndex())) {
            case "Administrador" -> 
                tipoUser = 1;
            case "Comum" -> 
                tipoUser = 0;
        }
        
        return tipoUser;
    }
    
    private void tabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuarioMouseClicked
        // TODO add your handling code here:
        if (tabelaUsuario.getSelectedRow() != -1) {
            Usuario u = model.pegaDadosLinha(tabelaUsuario.getSelectedRow());
            botaoInativar.setVisible(true);
        
            caixaInsSenha.setText(u.getSenhausuario());
            caixaInsNome.setText(u.getNomecompleto());
            caixaInsCpf.setText(u.getCpf());
            
            tipoComboBox.setSelectedIndex(u.getTipousuario());
            caixaInsCargo.setText(u.getCargo());
            
            URL ativar = getClass().getResource("/Logo/Ativar.png");
            Icon activate = new ImageIcon(ativar);
            URL desativar = getClass().getResource("/Logo/Inativar.png");
            Icon desactivate = new ImageIcon(desativar);
            
            if (u.getSituacaousuario() == 0) {
                botaoInativar.setIcon(activate);
                botaoInativar.setText("Ativar");
            } else{
                botaoInativar.setIcon(desactivate);
                botaoInativar.setText("Inativar");
            }
            
        consultaUsuario(u.getCodusuario(), u.getSenhausuario(), 
                u.getTipousuario(), u.getCargo());
        }
    }//GEN-LAST:event_tabelaUsuarioMouseClicked

    public void consultaUsuario(int cod ,String senha, int tipo, String cargo){
            consultaItens.setVisible(true);
            
            consultaSenha.setText(senha);
            consultaTipo.setText(String.valueOf(tipo));
            consultaCargo.setText(cargo);
            consultaCod.setText(String.valueOf(cod));
    }
    
    private void botaoInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInativarActionPerformed
        // TODO add your handling code here:
        Usuario u = model.pegaDadosLinha(tabelaUsuario.getSelectedRow());
        
        if (botaoInativar.getText() == "Inativar") {
            UsuarioDAO dao = new UsuarioDAO();
            dao.inativar(u);
            limpacampos();
            
        } else {
            UsuarioDAO dao = new UsuarioDAO();
            dao.ativar(u);
            limpacampos();
        }
    }//GEN-LAST:event_botaoInativarActionPerformed

    private void botaoLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpar1ActionPerformed
        // TODO add your handling code here:
        limpacampos();
    }//GEN-LAST:event_botaoLimpar1ActionPerformed

    private void caixaInsPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caixaInsPesquisarKeyReleased
        // TODO add your handling code here:
        if (!"".equals(caixaInsPesquisar.getText())) {
            model.recarregaTabelaPesq(caixaInsPesquisar.getText());
        } else {
            model.recarregaTabela();
        }
    }//GEN-LAST:event_caixaInsPesquisarKeyReleased

    private void botaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseClicked
        // TODO add your handling code here:
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarMouseClicked

    private void botaoVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_botaoVoltarMouseEntered

    private void botaoVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_botaoVoltarMouseExited

    public void organizarCaixasInserir() throws ParseException{
        caixaInsCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory
        (new javax.swing.text.MaskFormatter("###.###.###-##")));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JanelaUsuario().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(JanelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void limpacampos(){
        caixaInsSenha.setText("");
        caixaInsNome.setText("");
        caixaInsCpf.setText("");
        caixaInsCargo.setText("");
        caixaInsNome.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoInativar;
    private javax.swing.JButton botaoLimpar1;
    private javax.swing.JLabel botaoVoltar;
    private javax.swing.JLabel caixaCPF1;
    private javax.swing.JLabel caixaCargo;
    private javax.swing.JLabel caixaConsultaCargo;
    private javax.swing.JLabel caixaConsultaCod;
    private javax.swing.JLabel caixaConsultaSenha;
    private javax.swing.JLabel caixaConsultaTipo;
    private javax.swing.JTextField caixaInsCargo;
    private javax.swing.JFormattedTextField caixaInsCpf;
    private javax.swing.JTextField caixaInsNome;
    private javax.swing.JTextField caixaInsPesquisar;
    private javax.swing.JTextField caixaInsSenha;
    private javax.swing.JLabel caixaPesquisar;
    private javax.swing.JLabel caixaSenhaUsuario;
    private javax.swing.JLabel caixaSenhaUsuario1;
    private javax.swing.JLabel caixaTipo;
    private javax.swing.JLabel caixaUsuario;
    private javax.swing.JLabel consultaCargo;
    private javax.swing.JLabel consultaCod;
    private javax.swing.JPanel consultaItens;
    private javax.swing.JLabel consultaSenha;
    private javax.swing.JLabel consultaTipo;
    private javax.swing.JLabel consultaUsuario;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUsuario;
    private javax.swing.JComboBox<String> tipoComboBox;
    // End of variables declaration//GEN-END:variables
}
