/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;
import API.ViaCepAPI;
import DAO.DrogariaDAO;
import Objetos.Drogaria;
import Model.DrogariaTableModel;
import Objetos.Endereco;
import Regex.ValidacaoRegex;
import java.awt.Cursor;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.hc.core5.http.ParseException;

/**
 *
 * @author miche
 */
public final class JanelaDrogaria extends javax.swing.JFrame {

    /**
     * Creates new form JanelaDrogaria
     */
    
    TelaInicial inicio;
    
    DrogariaTableModel model = new DrogariaTableModel();
    
    public JanelaDrogaria() throws java.text.ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        
        consultaItens.setVisible(false);
        botaoInativarDrog.setVisible(false);
        
        organizarCaixasInserir();
        
        organizarColunas();
    }
    
    public JanelaDrogaria(TelaInicial inicio) throws java.text.ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        tabelaDrogaria.setModel(model);
        this.inicio = inicio;
        
        consultaItens.setVisible(false);
        botaoInativarDrog.setVisible(false);
        
        organizarCaixasInserir();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caixaInsCidDrog = new javax.swing.JTextField();
        caixaInsEstDrog = new javax.swing.JTextField();
        botaoCadastrarDrog = new javax.swing.JButton();
        botaoAlterarDrog = new javax.swing.JButton();
        botaoInativarDrog = new javax.swing.JButton();
        caixaBairroDrogaria = new javax.swing.JLabel();
        caixaCidadeDrogaria = new javax.swing.JLabel();
        caixaEstadoDrogaria = new javax.swing.JLabel();
        caixaCEPDrogaria = new javax.swing.JLabel();
        caixaInsNomeDrog = new javax.swing.JTextField();
        caixaInsRuaDrog = new javax.swing.JTextField();
        caixaInsNumDrog = new javax.swing.JTextField();
        caixaDrogaria = new javax.swing.JLabel();
        caixaCNPJDrogaria = new javax.swing.JLabel();
        caixaNomeDrogaria = new javax.swing.JLabel();
        caixaRuaDrogaria = new javax.swing.JLabel();
        caixaNumDrogaria = new javax.swing.JLabel();
        caixaCompDrogaria = new javax.swing.JLabel();
        caixaInsCompDrog = new javax.swing.JTextField();
        caixaInsBairroDrog = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDrogaria = new javax.swing.JTable();
        botaoLimpar3 = new javax.swing.JButton();
        caixaPesquisar = new javax.swing.JLabel();
        caixaInsPesquisar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        caixaInsCEPDrog = new javax.swing.JFormattedTextField();
        caixaInsCNPJDrog = new javax.swing.JFormattedTextField();
        consultaItens = new javax.swing.JPanel();
        consultaRua = new javax.swing.JLabel();
        consultaCidade = new javax.swing.JLabel();
        consultaBairro = new javax.swing.JLabel();
        caixaConsultaBairro = new javax.swing.JLabel();
        caixaConsultaCidade = new javax.swing.JLabel();
        caixaConsultaRua = new javax.swing.JLabel();
        consultaDrogaria = new javax.swing.JLabel();
        caixaConsultaNum = new javax.swing.JLabel();
        consultaNum = new javax.swing.JLabel();
        caixaConsultaEstado = new javax.swing.JLabel();
        consultaEstado = new javax.swing.JLabel();
        caixaConsultaCEP = new javax.swing.JLabel();
        consultaCEP = new javax.swing.JLabel();
        caixaConsultaCod = new javax.swing.JLabel();
        consultaCod = new javax.swing.JLabel();
        caixaConsultaComplemento = new javax.swing.JLabel();
        consultaComplemento = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        botaoCadastrarDrog.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoCadastrarDrog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Adicionar.png"))); // NOI18N
        botaoCadastrarDrog.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoCadastrarDrog.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoCadastrarDrog.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoCadastrarDrog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarDrogActionPerformed(evt);
            }
        });

        botaoAlterarDrog.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoAlterarDrog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Alterar.png"))); // NOI18N
        botaoAlterarDrog.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoAlterarDrog.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoAlterarDrog.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoAlterarDrog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarDrogActionPerformed(evt);
            }
        });

        botaoInativarDrog.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoInativarDrog.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoInativarDrog.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoInativarDrog.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoInativarDrog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInativarDrogActionPerformed(evt);
            }
        });

        caixaBairroDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaBairroDrogaria.setText("Bairro");

        caixaCidadeDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCidadeDrogaria.setText("Cidade");

        caixaEstadoDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaEstadoDrogaria.setText("Estado");

        caixaCEPDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCEPDrogaria.setText("CEP");

        caixaDrogaria.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        caixaDrogaria.setText("DROGARIA");

        caixaCNPJDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCNPJDrogaria.setText("CNPJ");

        caixaNomeDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaNomeDrogaria.setText("Nome");

        caixaRuaDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaRuaDrogaria.setText("Rua");

        caixaNumDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaNumDrogaria.setText("Número");

        caixaCompDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCompDrogaria.setText("Complemento");

        tabelaDrogaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelaDrogaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaDrogaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDrogariaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDrogaria);

        botaoLimpar3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoLimpar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Limpar.png"))); // NOI18N
        botaoLimpar3.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoLimpar3.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoLimpar3.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoLimpar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpar3ActionPerformed(evt);
            }
        });

        caixaPesquisar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaPesquisar.setText("Pesquisar ");

        caixaInsPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caixaInsPesquisarKeyReleased(evt);
            }
        });

        caixaInsCEPDrog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caixaInsCEPDrogKeyReleased(evt);
            }
        });

        consultaItens.setBackground(new java.awt.Color(255, 255, 255));
        consultaItens.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 46, 138), 4, true));

        consultaRua.setBackground(new java.awt.Color(0, 0, 0));
        consultaRua.setText("Rua");

        consultaCidade.setText("Cidade");

        consultaBairro.setText("Bairro");

        caixaConsultaBairro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caixaConsultaBairro.setText("Bairro");

        caixaConsultaCidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caixaConsultaCidade.setText("Cidade");

        caixaConsultaRua.setBackground(new java.awt.Color(0, 0, 0));
        caixaConsultaRua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caixaConsultaRua.setText("Rua");

        consultaDrogaria.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        consultaDrogaria.setText("CONSULTA DROGARIA");

        caixaConsultaNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caixaConsultaNum.setText("Número");

        consultaNum.setText("Número");

        caixaConsultaEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caixaConsultaEstado.setText("Estado");

        consultaEstado.setText("Estado");

        caixaConsultaCEP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caixaConsultaCEP.setText("CEP");

        consultaCEP.setText("CEP");

        caixaConsultaCod.setBackground(new java.awt.Color(0, 0, 0));
        caixaConsultaCod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caixaConsultaCod.setText("Código drogaria");

        consultaCod.setBackground(new java.awt.Color(0, 0, 0));
        consultaCod.setText("Código drogaria");

        caixaConsultaComplemento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caixaConsultaComplemento.setText("Complemento");

        consultaComplemento.setText("Complemento");

        javax.swing.GroupLayout consultaItensLayout = new javax.swing.GroupLayout(consultaItens);
        consultaItens.setLayout(consultaItensLayout);
        consultaItensLayout.setHorizontalGroup(
            consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaItensLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaItensLayout.createSequentialGroup()
                        .addComponent(caixaConsultaCod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultaCod))
                    .addComponent(consultaDrogaria)
                    .addComponent(caixaConsultaBairro)
                    .addComponent(caixaConsultaNum)
                    .addGroup(consultaItensLayout.createSequentialGroup()
                        .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(caixaConsultaRua, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(consultaItensLayout.createSequentialGroup()
                                    .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(caixaConsultaEstado)
                                        .addComponent(caixaConsultaCidade))
                                    .addGap(12, 12, 12))
                                .addComponent(caixaConsultaCEP, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(caixaConsultaComplemento))
                        .addGap(20, 20, 20)
                        .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultaNum)
                            .addComponent(consultaRua)
                            .addComponent(consultaBairro)
                            .addComponent(consultaCidade)
                            .addComponent(consultaEstado)
                            .addComponent(consultaCEP)
                            .addComponent(consultaComplemento))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaItensLayout.setVerticalGroup(
            consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaItensLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(consultaDrogaria)
                .addGap(18, 18, 18)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaCod)
                    .addComponent(consultaCod))
                .addGap(4, 4, 4)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaRua)
                    .addComponent(caixaConsultaRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaNum)
                    .addComponent(consultaNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaBairro)
                    .addComponent(consultaBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaComplemento)
                    .addComponent(consultaComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaCidade)
                    .addComponent(consultaCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaEstado)
                    .addComponent(consultaEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaConsultaCEP)
                    .addComponent(consultaCEP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Voltar.png"))); // NOI18N
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caixaNomeDrogaria)
                                .addGap(56, 56, 56)
                                .addComponent(caixaInsNomeDrog, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caixaCEPDrogaria)
                                    .addComponent(caixaRuaDrogaria)
                                    .addComponent(caixaCidadeDrogaria)
                                    .addComponent(caixaEstadoDrogaria)
                                    .addComponent(caixaNumDrogaria)
                                    .addComponent(caixaCompDrogaria)
                                    .addComponent(caixaCNPJDrogaria)
                                    .addComponent(caixaBairroDrogaria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(caixaInsBairroDrog, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                    .addComponent(caixaInsNumDrog)
                                    .addComponent(caixaInsEstDrog)
                                    .addComponent(caixaInsCEPDrog)
                                    .addComponent(caixaInsCidDrog)
                                    .addComponent(caixaInsRuaDrog)
                                    .addComponent(caixaInsCNPJDrog, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(caixaInsCompDrog)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(caixaDrogaria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoCadastrarDrog, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoAlterarDrog, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoLimpar3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoInativarDrog, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(consultaItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caixaPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(caixaInsPesquisar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixaDrogaria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsNomeDrog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaNomeDrogaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsCNPJDrog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaCNPJDrogaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsCEPDrog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaCEPDrogaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(caixaInsRuaDrog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaRuaDrogaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsCidDrog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaCidadeDrogaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsEstDrog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaEstadoDrogaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsNumDrog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaNumDrogaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsCompDrog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaCompDrogaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsBairroDrog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaBairroDrogaria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoLimpar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoCadastrarDrog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAlterarDrog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoInativarDrog, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(consultaItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaPesquisar)
                    .addComponent(caixaInsPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarDrogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarDrogActionPerformed
        // TODO add your handling code here:
        Drogaria d = new Drogaria();
        DrogariaDAO dao = new DrogariaDAO();
        
        try {
            d.setCnpjdrogaria(caixaInsCNPJDrog.getText());
            d.setNomedrogaria(caixaInsNomeDrog.getText());
            d.setRuadrogaria(caixaInsRuaDrog.getText());
            d.setNumerodrogaria(caixaInsNumDrog.getText());
            d.setComplementodrogaria(caixaInsCompDrog.getText());
            d.setBairrodrogaria(caixaInsBairroDrog.getText());
            d.setCidadedrogaria(caixaInsCidDrog.getText());
            d.setEstadodrogaria(caixaInsEstDrog.getText());
            d.setCepdrogaria(caixaInsCEPDrog.getText());
            dao.criar(d);
            model.recarregaTabela();
            limpacampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha em efetuar cadastro: " + e);
        }
    }//GEN-LAST:event_botaoCadastrarDrogActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        model.recarregaTabela();
    }//GEN-LAST:event_formWindowActivated

    private void botaoAlterarDrogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarDrogActionPerformed
        // TODO add your handling code here:
        if(tabelaDrogaria.getSelectedRow() != -1){
            model.setValueAt(caixaInsCNPJDrog.getText(), tabelaDrogaria.getSelectedRow(), 2);
            model.setValueAt(caixaInsNomeDrog.getText(), tabelaDrogaria.getSelectedRow(), 3);
            model.setValueAt(caixaInsRuaDrog.getText(), tabelaDrogaria.getSelectedRow(), 4);
            model.setValueAt(caixaInsNumDrog.getText(), tabelaDrogaria.getSelectedRow(), 5);
            model.setValueAt(caixaInsCompDrog.getText(), tabelaDrogaria.getSelectedRow(), 6);
            model.setValueAt(caixaInsBairroDrog.getText(), tabelaDrogaria.getSelectedRow(), 7);
            model.setValueAt(caixaInsCidDrog.getText(), tabelaDrogaria.getSelectedRow(), 8);
            model.setValueAt(caixaInsEstDrog.getText(), tabelaDrogaria.getSelectedRow(), 9);
            model.setValueAt(caixaInsCEPDrog.getText(), tabelaDrogaria.getSelectedRow(), 10);
            
            Drogaria d = model.pegaDadosLinha(tabelaDrogaria.getSelectedRow());
            DrogariaDAO dao = new DrogariaDAO();
            
            dao.atualizar(d);
            limpacampos();
            model.recarregaTabela();
        } 
    }//GEN-LAST:event_botaoAlterarDrogActionPerformed

    private void tabelaDrogariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDrogariaMouseClicked
        // TODO add your handling code here:
        if (tabelaDrogaria.getSelectedRow() != -1) {
            Drogaria d = model.pegaDadosLinha(tabelaDrogaria.getSelectedRow());
            caixaInsCNPJDrog.setText(d.getCnpjdrogaria());
            caixaInsNomeDrog.setText(d.getNomedrogaria());
            caixaInsRuaDrog.setText(d.getRuadrogaria());
            caixaInsNumDrog.setText(d.getNumerodrogaria());
            caixaInsCompDrog.setText(d.getComplementodrogaria());
            caixaInsBairroDrog.setText(d.getBairrodrogaria());
            caixaInsCidDrog.setText(d.getCidadedrogaria());
            caixaInsEstDrog.setText(d.getEstadodrogaria());
            caixaInsCEPDrog.setText(d.getCepdrogaria());
            
            botaoInativarDrog.setVisible(true);
            
            URL ativar = getClass().getResource("/Logo/Ativar.png");
            Icon activate = new ImageIcon(ativar);
            URL desativar = getClass().getResource("/Logo/Inativar.png");
            Icon desactivate = new ImageIcon(desativar);
            
            if (d.getSituacaodrogaria() == 0) {
                botaoInativarDrog.setText("Ativar");
                botaoInativarDrog.setIcon(activate);
            } else {
                botaoInativarDrog.setText("Inativar");
                botaoInativarDrog.setIcon(desactivate);
            }
            
//            switch (d.getSituacaodrogaria()) {
//                case 0 ->botaoInativarDrog.setIcon(activate);
//                case 1 -> botaoInativarDrog.setIcon(desactivate);
//            }
            
            consultaDrogaria(d.getCoddrogaria(),d.getRuadrogaria(), d.getNumerodrogaria(),d.getBairrodrogaria(), 
                    d.getCidadedrogaria(), d.getEstadodrogaria(), d.getCepdrogaria(), d.getComplementodrogaria());
            
        }
    }//GEN-LAST:event_tabelaDrogariaMouseClicked

    public void consultaDrogaria(int cod, String rua, String num, String bairro, 
            String cidade, String estado, String CEP, String complemento){
        consultaItens.setVisible(true);
        consultaRua.setText(rua);
        consultaNum.setText(num);
        consultaBairro.setText(bairro);
        consultaCidade.setText(cidade);
        consultaEstado.setText(estado);
        consultaCEP.setText(CEP);   
        consultaCod.setText(String.valueOf(cod));
        
        if (complemento.isEmpty()) {
            consultaComplemento.setText("Sem complemento");
        } else {
            consultaComplemento.setText(complemento);
        }
    }
    
    private void botaoLimpar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpar3ActionPerformed
        // TODO add your handling code here:
        limpacampos();
    }//GEN-LAST:event_botaoLimpar3ActionPerformed

    private void botaoInativarDrogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInativarDrogActionPerformed
        // TODO add your handling code here:
        Drogaria d = model.pegaDadosLinha(tabelaDrogaria.getSelectedRow());
        
        if ("Inativar".equals(botaoInativarDrog.getText())) {
            DrogariaDAO dao = new DrogariaDAO();
            dao.inativar(d);
            limpacampos();
        } else {
            DrogariaDAO dao = new DrogariaDAO();
            dao.ativar(d);
            limpacampos();
        }
    }//GEN-LAST:event_botaoInativarDrogActionPerformed

    private void caixaInsPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caixaInsPesquisarKeyReleased
        // TODO add your handling code here:
        if (!"".equals(caixaInsPesquisar.getText())) {
            model.recarregaTabelaPesq(caixaInsPesquisar.getText());
        } else {
            model.recarregaTabela();
        }
    }//GEN-LAST:event_caixaInsPesquisarKeyReleased

    private void caixaInsCEPDrogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caixaInsCEPDrogKeyReleased
        // TODO add your handling code here:
        ViaCepAPI vcAPI = new ViaCepAPI();
        Boolean valCep = new ValidacaoRegex().validarCep(caixaInsCEPDrog.getText());

        if (valCep) {
            try {
                Endereco endereco = vcAPI.getEndereco(caixaInsCEPDrog.getText());

                caixaInsBairroDrog.setText(endereco.getBairro());
                caixaInsCidDrog.setText(endereco.getLocalidade());
                caixaInsCompDrog.setText(endereco.getComplemento());
                caixaInsEstDrog.setText(endereco.getUf());
                caixaInsRuaDrog.setText(endereco.getLogradouro());

            } catch (IOException | ParseException e) {
               JOptionPane.showMessageDialog(null, "Falha em obter dados do CEP: " + e);
            }
        } else {
            caixaInsBairroDrog.setText("");
            caixaInsCidDrog.setText("");
            caixaInsCompDrog.setText("");
            caixaInsEstDrog.setText("");
            caixaInsRuaDrog.setText("");
        }
    }//GEN-LAST:event_caixaInsCEPDrogKeyReleased

    private void botaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseClicked
        // TODO add your handling code here:
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarMouseClicked

    private void botaoVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_botaoVoltarMouseEntered

    private void botaoVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_botaoVoltarMouseExited
    
    public void organizarCaixasInserir() throws java.text.ParseException{
        caixaInsCEPDrog.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory
        (new javax.swing.text.MaskFormatter("#####-###")));
        
//        caixaInsData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory
//        (new javax.swing.text.MaskFormatter("##/##/####")));
        
        caixaInsCNPJDrog.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory
        (new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaDrogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaDrogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaDrogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaDrogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JanelaDrogaria().setVisible(true);
                } catch (java.text.ParseException ex) {
                    Logger.getLogger(JanelaDrogaria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void organizarColunas(){
        tabelaDrogaria.setModel(model);
        
        //tabelaDrogaria.getTableHeader().setResizingAllowed(false);
        
        tabelaDrogaria.getColumnModel().getColumn(0).setPreferredWidth(-15);
        
        
//        tabelaDrogaria.getColumnModel().getColumn(1).setPreferredWidth(5);
//        tabelaDrogaria.getColumnModel().getColumn(2).setPreferredWidth(150);
//        tabelaDrogaria.getColumnModel().getColumn(3).setPreferredWidth(55);
//        tabelaDrogaria.getColumnModel().getColumn(4).setPreferredWidth(70);
//        tabelaDrogaria.getColumnModel().getColumn(5).setPreferredWidth(150);
//        tabelaDrogaria.getColumnModel().getColumn(6).setPreferredWidth(105);
    }
    
    public void limpacampos(){
        caixaInsCNPJDrog.setText("");
        caixaInsNomeDrog.setText("");
        caixaInsRuaDrog.setText("");
        caixaInsNumDrog.setText("");
        caixaInsCompDrog.setText("");
        caixaInsBairroDrog.setText("");
        caixaInsCidDrog.setText("");
        caixaInsEstDrog.setText("");
        caixaInsCEPDrog.setText("");
        
        caixaInsNomeDrog.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarDrog;
    private javax.swing.JButton botaoCadastrarDrog;
    private javax.swing.JButton botaoInativarDrog;
    private javax.swing.JButton botaoLimpar3;
    private javax.swing.JLabel botaoVoltar;
    private javax.swing.JLabel caixaBairroDrogaria;
    private javax.swing.JLabel caixaCEPDrogaria;
    private javax.swing.JLabel caixaCNPJDrogaria;
    private javax.swing.JLabel caixaCidadeDrogaria;
    private javax.swing.JLabel caixaCompDrogaria;
    private javax.swing.JLabel caixaConsultaBairro;
    private javax.swing.JLabel caixaConsultaCEP;
    private javax.swing.JLabel caixaConsultaCidade;
    private javax.swing.JLabel caixaConsultaCod;
    private javax.swing.JLabel caixaConsultaComplemento;
    private javax.swing.JLabel caixaConsultaEstado;
    private javax.swing.JLabel caixaConsultaNum;
    private javax.swing.JLabel caixaConsultaRua;
    private javax.swing.JLabel caixaDrogaria;
    private javax.swing.JLabel caixaEstadoDrogaria;
    private javax.swing.JTextField caixaInsBairroDrog;
    private javax.swing.JFormattedTextField caixaInsCEPDrog;
    private javax.swing.JFormattedTextField caixaInsCNPJDrog;
    private javax.swing.JTextField caixaInsCidDrog;
    private javax.swing.JTextField caixaInsCompDrog;
    private javax.swing.JTextField caixaInsEstDrog;
    private javax.swing.JTextField caixaInsNomeDrog;
    private javax.swing.JTextField caixaInsNumDrog;
    private javax.swing.JTextField caixaInsPesquisar;
    private javax.swing.JTextField caixaInsRuaDrog;
    private javax.swing.JLabel caixaNomeDrogaria;
    private javax.swing.JLabel caixaNumDrogaria;
    private javax.swing.JLabel caixaPesquisar;
    private javax.swing.JLabel caixaRuaDrogaria;
    private javax.swing.JLabel consultaBairro;
    private javax.swing.JLabel consultaCEP;
    private javax.swing.JLabel consultaCidade;
    private javax.swing.JLabel consultaCod;
    private javax.swing.JLabel consultaComplemento;
    private javax.swing.JLabel consultaDrogaria;
    private javax.swing.JLabel consultaEstado;
    private javax.swing.JPanel consultaItens;
    private javax.swing.JLabel consultaNum;
    private javax.swing.JLabel consultaRua;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDrogaria;
    // End of variables declaration//GEN-END:variables
}
