/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;
import API.ViaCepAPI;
import Model.FornecedorTableModel;
import Objetos.Fornecedor;
import DAO.FornecedorDAO;
import Objetos.Endereco;
import Regex.ValidacaoRegex;
import java.awt.Cursor;
import java.io.IOException;
import java.net.URL;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user_acronus
 */
public final class JanelaFornecedor extends javax.swing.JFrame {
    
    TelaInicial inicio;
    
    FornecedorTableModel model = new FornecedorTableModel();
    FornecedorDAO dao = new FornecedorDAO();

    /**
     * Creates new form JanelaFornecedor
     * @throws java.text.ParseException
     */
    public JanelaFornecedor() throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        tabelaFornecedores.setModel(model);
        botaoInativarForn.setVisible(false);
        consultaItens.setVisible(false);
        
        organizarCaixasInserir();
    }
    
    public JanelaFornecedor(TelaInicial inicio) throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        tabelaFornecedores.setModel(model);
        botaoInativarForn.setVisible(false);
        consultaItens.setVisible(false);
        
        organizarCaixasInserir();
        this.inicio = inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caixaFornecedor = new javax.swing.JLabel();
        caixaIEFornecedor = new javax.swing.JLabel();
        caixaCNPJFornecedor = new javax.swing.JLabel();
        caixaNomeFornecedor = new javax.swing.JLabel();
        caixaRuaFornecedor = new javax.swing.JLabel();
        caixaNumFornecedor = new javax.swing.JLabel();
        caixaCompFornecedor = new javax.swing.JLabel();
        caixaBairroFornecedor = new javax.swing.JLabel();
        caixaCidadeFornecedor = new javax.swing.JLabel();
        caixaEstadoFornecedor = new javax.swing.JLabel();
        caixaCEPFornecedor = new javax.swing.JLabel();
        caixaInsNomeForn = new javax.swing.JTextField();
        caixaInsRuaForn = new javax.swing.JTextField();
        caixaInsNumForn = new javax.swing.JTextField();
        caixaInsCompForn = new javax.swing.JTextField();
        caixaInsBairroForn = new javax.swing.JTextField();
        caixaInsCidForn = new javax.swing.JTextField();
        caixaInsEstForn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFornecedores = new javax.swing.JTable();
        botaoCadastrarForn = new javax.swing.JButton();
        botaoAlterarForn = new javax.swing.JButton();
        botaoInativarForn = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        caixaPesquisar = new javax.swing.JLabel();
        caixaInsPesquisar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        caixaInsCEPForn = new javax.swing.JFormattedTextField();
        caixaInsCNPJForn = new javax.swing.JFormattedTextField();
        caixaInsIEForn = new javax.swing.JFormattedTextField();
        consultaItens = new javax.swing.JPanel();
        consultaFornecedor = new javax.swing.JLabel();
        caixaConsultaCod = new javax.swing.JLabel();
        consultaRua = new javax.swing.JLabel();
        caixaConsultaNum = new javax.swing.JLabel();
        consultaNum = new javax.swing.JLabel();
        caixaConsultaBairro = new javax.swing.JLabel();
        consultaBairro = new javax.swing.JLabel();
        caixaConsultaCidade = new javax.swing.JLabel();
        consultaCidade = new javax.swing.JLabel();
        consultaEstado = new javax.swing.JLabel();
        caixaConsultaEstado = new javax.swing.JLabel();
        caixaConsultaCEP = new javax.swing.JLabel();
        consultaCEP = new javax.swing.JLabel();
        caixaConsultaRua = new javax.swing.JLabel();
        consultaCod = new javax.swing.JLabel();
        caixaConsultaComplemento = new javax.swing.JLabel();
        consultaComplemento = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        caixaFornecedor.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        caixaFornecedor.setText("FORNECEDOR");

        caixaIEFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaIEFornecedor.setText("Inscrição Estadual");

        caixaCNPJFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCNPJFornecedor.setText("CNPJ:");

        caixaNomeFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaNomeFornecedor.setText("Nome:");

        caixaRuaFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaRuaFornecedor.setText("Rua:");

        caixaNumFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaNumFornecedor.setText("Número:");

        caixaCompFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCompFornecedor.setText("Complemento:");

        caixaBairroFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaBairroFornecedor.setText("Bairro:");

        caixaCidadeFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCidadeFornecedor.setText("Cidade:");

        caixaEstadoFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaEstadoFornecedor.setText("Estado:");

        caixaCEPFornecedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaCEPFornecedor.setText("CEP:");

        caixaInsNomeForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        caixaInsRuaForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaInsRuaForn.setActionCommand("<Not Set>");

        caixaInsNumForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        caixaInsCompForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        caixaInsBairroForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        caixaInsCidForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        caixaInsEstForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tabelaFornecedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelaFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFornecedores);

        botaoCadastrarForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoCadastrarForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Adicionar.png"))); // NOI18N
        botaoCadastrarForn.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoCadastrarForn.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoCadastrarForn.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoCadastrarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarFornActionPerformed(evt);
            }
        });

        botaoAlterarForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoAlterarForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Alterar.png"))); // NOI18N
        botaoAlterarForn.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoAlterarForn.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoAlterarForn.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoAlterarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarFornActionPerformed(evt);
            }
        });

        botaoInativarForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoInativarForn.setText("Inativar");
        botaoInativarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInativarFornActionPerformed(evt);
            }
        });

        botaoLimpar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Limpar.png"))); // NOI18N
        botaoLimpar.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoLimpar.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoLimpar.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        caixaPesquisar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaPesquisar.setText("Pesquisar");

        caixaInsPesquisar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaInsPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caixaInsPesquisarKeyReleased(evt);
            }
        });

        caixaInsCEPForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        caixaInsCEPForn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caixaInsCEPFornKeyReleased(evt);
            }
        });

        caixaInsCNPJForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        caixaInsIEForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        consultaItens.setBackground(new java.awt.Color(255, 255, 255));
        consultaItens.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 46, 138), 4, true));
        consultaItens.setMaximumSize(new java.awt.Dimension(253, 326));
        consultaItens.setMinimumSize(new java.awt.Dimension(253, 326));
        consultaItens.setName(""); // NOI18N

        consultaFornecedor.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        consultaFornecedor.setText("CONSULTA FORNECEDOR");

        caixaConsultaCod.setBackground(new java.awt.Color(0, 0, 0));
        caixaConsultaCod.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaCod.setText("Código fornecedor");

        consultaRua.setBackground(new java.awt.Color(0, 0, 0));
        consultaRua.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaRua.setText("Rua");

        caixaConsultaNum.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaNum.setText("Número");

        consultaNum.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaNum.setText("Número");

        caixaConsultaBairro.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaBairro.setText("Bairro");

        consultaBairro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaBairro.setText("Bairro");

        caixaConsultaCidade.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaCidade.setText("Cidade");

        consultaCidade.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaCidade.setText("Cidade");

        consultaEstado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaEstado.setText("Estado");

        caixaConsultaEstado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaEstado.setText("Estado");

        caixaConsultaCEP.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaCEP.setText("CEP");

        consultaCEP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaCEP.setText("CEP");

        caixaConsultaRua.setBackground(new java.awt.Color(0, 0, 0));
        caixaConsultaRua.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaRua.setText("Rua");

        consultaCod.setBackground(new java.awt.Color(0, 0, 0));
        consultaCod.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaCod.setText("Código");

        caixaConsultaComplemento.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        caixaConsultaComplemento.setText("Complemento");

        consultaComplemento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        consultaComplemento.setText("Complemento");

        javax.swing.GroupLayout consultaItensLayout = new javax.swing.GroupLayout(consultaItens);
        consultaItens.setLayout(consultaItensLayout);
        consultaItensLayout.setHorizontalGroup(
            consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaItensLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultaFornecedor)
                    .addGroup(consultaItensLayout.createSequentialGroup()
                        .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaConsultaCod)
                            .addComponent(caixaConsultaRua)
                            .addComponent(caixaConsultaNum)
                            .addComponent(caixaConsultaBairro)
                            .addComponent(caixaConsultaCidade)
                            .addComponent(caixaConsultaEstado)
                            .addComponent(caixaConsultaCEP)
                            .addComponent(caixaConsultaComplemento))
                        .addGap(18, 18, 18)
                        .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultaComplemento)
                            .addComponent(consultaRua)
                            .addComponent(consultaCod)
                            .addComponent(consultaNum)
                            .addComponent(consultaBairro)
                            .addComponent(consultaCidade)
                            .addComponent(consultaEstado)
                            .addComponent(consultaCEP))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaItensLayout.setVerticalGroup(
            consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaItensLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultaFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaCod)
                    .addComponent(consultaCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaRua)
                    .addComponent(consultaRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaNum)
                    .addComponent(consultaNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaBairro)
                    .addComponent(consultaBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaComplemento)
                    .addComponent(consultaComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaCidade)
                    .addComponent(consultaCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaEstado)
                    .addComponent(consultaEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaConsultaCEP)
                    .addComponent(consultaCEP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Voltar.png"))); // NOI18N
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoVoltar)
                                .addGap(18, 18, 18)
                                .addComponent(caixaFornecedor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(caixaPesquisar)
                                    .addGap(18, 18, 18)
                                    .addComponent(caixaInsPesquisar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(caixaNomeFornecedor)
                                                .addGap(82, 82, 82)
                                                .addComponent(caixaInsNomeForn))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(caixaCNPJFornecedor)
                                                            .addComponent(caixaRuaFornecedor)
                                                            .addComponent(caixaNumFornecedor))
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(caixaBairroFornecedor)
                                                        .addComponent(caixaCompFornecedor)
                                                        .addComponent(caixaCidadeFornecedor)
                                                        .addComponent(caixaEstadoFornecedor)
                                                        .addComponent(caixaCEPFornecedor)))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(caixaInsEstForn, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(caixaInsCidForn, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(caixaInsBairroForn, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(caixaInsCompForn, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(caixaInsNumForn, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(caixaInsRuaForn, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(caixaInsCNPJForn)
                                                    .addComponent(caixaInsCEPForn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(botaoCadastrarForn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoAlterarForn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botaoInativarForn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(caixaIEFornecedor)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(caixaInsIEForn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(12, 12, 12)
                                    .addComponent(consultaItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 29, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caixaFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaNomeFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsIEForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaIEFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsCNPJForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaCNPJFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsRuaForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaRuaFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsNumForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaNumFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsCompForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaCompFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsBairroForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaBairroFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsCidForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaCidadeFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsEstForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaEstadoFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaInsCEPForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaCEPFornecedor))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botaoCadastrarForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoAlterarForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botaoInativarForn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(consultaItens, javax.swing.GroupLayout.PREFERRED_SIZE, 321, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaPesquisar)
                    .addComponent(caixaInsPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarFornActionPerformed
        // TODO add your handling code here:
        Fornecedor f = new Fornecedor();
        FornecedorDAO dao = new FornecedorDAO();
        
        try {
            f.setInscricaoestadualfornecedor(caixaInsIEForn.getText());
            f.setCnpjfornecedor(caixaInsCNPJForn.getText());
            f.setNomefornecedor(caixaInsNomeForn.getText());
            f.setRuafornecedor(caixaInsRuaForn.getText());
            f.setNumerofornecedor(caixaInsNumForn.getText());
            f.setComplementofornecedor(caixaInsCompForn.getText());
            f.setBairrofornecedor(caixaInsBairroForn.getText());
            f.setCidadefornecedor(caixaInsCidForn.getText());
            f.setEstadofornecedor(caixaInsEstForn.getText());
            f.setCepfornecedor(caixaInsCEPForn.getText());
            dao.criar(f);
            model.recarregaTabela();
            limpaCampos();
            
        } catch (Exception e) {
            System.out.println("Erro: " + e);
        }
    }//GEN-LAST:event_botaoCadastrarFornActionPerformed

    private void botaoAlterarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarFornActionPerformed
        // TODO add your handling code here:
        if (tabelaFornecedores.getSelectedRow() != -1) {
            model.setValueAt(caixaInsIEForn.getText(), tabelaFornecedores.getSelectedRow(), 2);
            model.setValueAt(caixaInsCNPJForn.getText(), tabelaFornecedores.getSelectedRow(), 3);
            model.setValueAt(caixaInsNomeForn.getText(), tabelaFornecedores.getSelectedRow(), 4);
            model.setValueAt(caixaInsRuaForn.getText(), tabelaFornecedores.getSelectedRow(), 5);
            model.setValueAt(caixaInsNumForn.getText(), tabelaFornecedores.getSelectedRow(), 6);
            model.setValueAt(caixaInsCompForn.getText(), tabelaFornecedores.getSelectedRow(), 7);
            model.setValueAt(caixaInsBairroForn.getText(), tabelaFornecedores.getSelectedRow(), 8);
            model.setValueAt(caixaInsCidForn.getText(), tabelaFornecedores.getSelectedRow(), 9);
            model.setValueAt(caixaInsEstForn.getText(), tabelaFornecedores.getSelectedRow(), 10);
            model.setValueAt(caixaInsCEPForn.getText(), tabelaFornecedores.getSelectedRow(), 11);
            
            Fornecedor f = model.pegaDadosLinha(tabelaFornecedores.getSelectedRow());
            FornecedorDAO dao = new FornecedorDAO();
            dao.atualizar(f);
            limpaCampos();
            model.recarregaTabela();
        }
    }//GEN-LAST:event_botaoAlterarFornActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        model.recarregaTabela();
    }//GEN-LAST:event_formWindowActivated

    private void botaoInativarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInativarFornActionPerformed
        // TODO add your handling code here:
        Fornecedor f = model.pegaDadosLinha(tabelaFornecedores.getSelectedRow());
        
        if ("Inativar".equals(botaoInativarForn.getText())) {
            FornecedorDAO dao = new FornecedorDAO();
            dao.inativar(f);
            limpaCampos();
            
        } else {
            FornecedorDAO dao = new FornecedorDAO();
            dao.ativar(f);
            limpaCampos();
        }
    }//GEN-LAST:event_botaoInativarFornActionPerformed

    private void tabelaFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFornecedoresMouseClicked
        // TODO add your handling code here:
        if (tabelaFornecedores.getSelectedRow() != -1) {

            botaoInativarForn.setVisible(true);

            Fornecedor f = model.pegaDadosLinha(tabelaFornecedores.getSelectedRow());
            caixaInsIEForn.setText(f.getInscricaoestadualfornecedor());
            caixaInsCNPJForn.setText(f.getCnpjfornecedor());
            caixaInsNomeForn.setText(f.getNomefornecedor());
            caixaInsRuaForn.setText(f.getRuafornecedor());
            caixaInsNumForn.setText(f.getNumerofornecedor());
            caixaInsCompForn.setText(f.getComplementofornecedor());
            caixaInsBairroForn.setText(f.getBairrofornecedor());
            caixaInsCidForn.setText(f.getCidadefornecedor());
            caixaInsEstForn.setText(f.getEstadofornecedor());
            caixaInsCEPForn.setText(f.getCepfornecedor());

            URL ativar = getClass().getResource("/Logo/Ativar.png");
            Icon activate = new ImageIcon(ativar);
            URL inativar = getClass().getResource("/Logo/Inativar.png");
            Icon desactivate = new ImageIcon(inativar);

            if (f.getSituacaofornecedor() == 0) {
                botaoInativarForn.setText("Ativar");
                botaoInativarForn.setIcon(activate);
            } else {
                botaoInativarForn.setText("Inativar");
                botaoInativarForn.setIcon(desactivate);
            }

    //        switch (f.getSituacaofornecedor()) {
    //            case 0 -> botaoInativarForn.setText("Ativar");
    //            case 1 -> botaoInativarForn.setText("Inativar");
    //            default -> {
    //                botaoInativarForn.setText("Ativar / Inativar");
    //            }
    //        }

            consultaFornecedor(f.getCodfornecedor(), f.getRuafornecedor(), f.getNumerofornecedor(),
                    f.getBairrofornecedor(), f.getCidadefornecedor(), f.getEstadofornecedor(),
                    f.getCepfornecedor(), f.getComplementofornecedor());
        }
    }//GEN-LAST:event_tabelaFornecedoresMouseClicked

    public void consultaFornecedor(int cod, String rua, String num, String bairro, 
            String cidade, String estado, String CEP, String complemento){
        consultaItens.setVisible(true);
        
        consultaRua.setText(rua);
        consultaNum.setText(num);
        consultaBairro.setText(bairro);
        consultaCidade.setText(cidade);
        consultaEstado.setText(estado);
        consultaCEP.setText(CEP);   
        consultaCod.setText(String.valueOf(cod));
        
        if (complemento.isEmpty()) {
            consultaComplemento.setText("Sem complemento");
        } else {
            consultaComplemento.setText(complemento);
        }
    }
    
    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void caixaInsPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caixaInsPesquisarKeyReleased
        // TODO add your handling code here:
        if (!"".equals(caixaInsPesquisar.getText())) {
            model.recarregaTabelaPesq(caixaInsPesquisar.getText());
        } else {
            model.recarregaTabela();
        }
    }//GEN-LAST:event_caixaInsPesquisarKeyReleased

    private void caixaInsCEPFornKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caixaInsCEPFornKeyReleased
        // TODO add your handling code here:
        ViaCepAPI vcAPI = new ViaCepAPI();
        Boolean valCep = new ValidacaoRegex().validarCep(caixaInsCEPForn.getText());

        if (valCep) {
            
            Endereco endereco;
            try {
                endereco = vcAPI.getEndereco(caixaInsCEPForn.getText());
                
                caixaInsBairroForn.setText(endereco.getBairro());
                caixaInsCidForn.setText(endereco.getLocalidade());
                caixaInsCompForn.setText(endereco.getComplemento());
                caixaInsEstForn.setText(endereco.getUf());
                caixaInsRuaForn.setText(endereco.getLogradouro());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Falha em obter dados do CEP: " + ex);
            } catch (org.apache.hc.core5.http.ParseException ex) {
                Logger.getLogger(JanelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            caixaInsBairroForn.setText("");
            caixaInsCidForn.setText("");
            caixaInsCompForn.setText("");
            caixaInsEstForn.setText("");
            caixaInsRuaForn.setText("");
        }
    }//GEN-LAST:event_caixaInsCEPFornKeyReleased

    private void botaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseClicked
        // TODO add your handling code here:
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarMouseClicked

    private void botaoVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_botaoVoltarMouseEntered

    private void botaoVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_botaoVoltarMouseExited

    public void organizarCaixasInserir() throws ParseException{
        caixaInsCEPForn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory
        (new javax.swing.text.MaskFormatter("#####-###")));
        
        caixaInsCNPJForn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory
        (new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        
        caixaInsIEForn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory
        (new javax.swing.text.MaskFormatter("########-##")));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JanelaFornecedor().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(JanelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void limpaCampos(){
        caixaInsIEForn.setText("");
        caixaInsCNPJForn.setText("");
        caixaInsNomeForn.setText("");
        caixaInsRuaForn.setText("");
        caixaInsNumForn.setText("");
        caixaInsCompForn.setText("");
        caixaInsBairroForn.setText("");
        caixaInsCidForn.setText("");
        caixaInsEstForn.setText("");
        caixaInsEstForn.setText("");
        caixaInsCEPForn.setText("");
        
        caixaInsNomeForn.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarForn;
    private javax.swing.JButton botaoCadastrarForn;
    private javax.swing.JButton botaoInativarForn;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JLabel botaoVoltar;
    private javax.swing.JLabel caixaBairroFornecedor;
    private javax.swing.JLabel caixaCEPFornecedor;
    private javax.swing.JLabel caixaCNPJFornecedor;
    private javax.swing.JLabel caixaCidadeFornecedor;
    private javax.swing.JLabel caixaCompFornecedor;
    private javax.swing.JLabel caixaConsultaBairro;
    private javax.swing.JLabel caixaConsultaCEP;
    private javax.swing.JLabel caixaConsultaCidade;
    private javax.swing.JLabel caixaConsultaCod;
    private javax.swing.JLabel caixaConsultaComplemento;
    private javax.swing.JLabel caixaConsultaEstado;
    private javax.swing.JLabel caixaConsultaNum;
    private javax.swing.JLabel caixaConsultaRua;
    private javax.swing.JLabel caixaEstadoFornecedor;
    private javax.swing.JLabel caixaFornecedor;
    private javax.swing.JLabel caixaIEFornecedor;
    private javax.swing.JTextField caixaInsBairroForn;
    private javax.swing.JFormattedTextField caixaInsCEPForn;
    private javax.swing.JFormattedTextField caixaInsCNPJForn;
    private javax.swing.JTextField caixaInsCidForn;
    private javax.swing.JTextField caixaInsCompForn;
    private javax.swing.JTextField caixaInsEstForn;
    private javax.swing.JFormattedTextField caixaInsIEForn;
    private javax.swing.JTextField caixaInsNomeForn;
    private javax.swing.JTextField caixaInsNumForn;
    private javax.swing.JTextField caixaInsPesquisar;
    private javax.swing.JTextField caixaInsRuaForn;
    private javax.swing.JLabel caixaNomeFornecedor;
    private javax.swing.JLabel caixaNumFornecedor;
    private javax.swing.JLabel caixaPesquisar;
    private javax.swing.JLabel caixaRuaFornecedor;
    private javax.swing.JLabel consultaBairro;
    private javax.swing.JLabel consultaCEP;
    private javax.swing.JLabel consultaCidade;
    private javax.swing.JLabel consultaCod;
    private javax.swing.JLabel consultaComplemento;
    private javax.swing.JLabel consultaEstado;
    private javax.swing.JLabel consultaFornecedor;
    private javax.swing.JPanel consultaItens;
    private javax.swing.JLabel consultaNum;
    private javax.swing.JLabel consultaRua;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFornecedores;
    // End of variables declaration//GEN-END:variables
}
