/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.NotaFiscalDAO;
import DAO.VendaDAO;
import Model.NotaFiscalTableModel;
import Objetos.NotaFiscal;
import Objetos.Venda;
import java.awt.Cursor;
import java.awt.Font;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author michel.matos
 */
public final class JanelaNf extends javax.swing.JFrame {
    
    TelaInicial inicio;
    VendaDAO vendDao = new VendaDAO();
    NotaFiscalTableModel model = new NotaFiscalTableModel();
    int clique = -1;

    /**
     * Creates new form JanelaNf
     */
    public JanelaNf() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tabelaNotaFiscal.setModel(model);
        model.recarregaTabela();
        formatar();
    }
    
    public JanelaNf(TelaInicial inicio) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.inicio = inicio;
        
        tabelaNotaFiscal.setModel(model);
        model.recarregaTabela();
        formatar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caixaNF = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaNotaFiscal = new javax.swing.JTable();
        botaoAlterarMed = new javax.swing.JButton();
        botaoConsultarItens = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        caixaNF.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        caixaNF.setText("NOTA FISCAL");

        tabelaNotaFiscal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelaNotaFiscal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaNotaFiscal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaNotaFiscalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaNotaFiscal);

        botaoAlterarMed.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botaoAlterarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/CancelarNF.png"))); // NOI18N
        botaoAlterarMed.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoAlterarMed.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoAlterarMed.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoAlterarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarMedActionPerformed(evt);
            }
        });

        botaoConsultarItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/ConsultaItens.png"))); // NOI18N
        botaoConsultarItens.setMaximumSize(new java.awt.Dimension(35, 35));
        botaoConsultarItens.setMinimumSize(new java.awt.Dimension(35, 35));
        botaoConsultarItens.setPreferredSize(new java.awt.Dimension(35, 35));
        botaoConsultarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarItensActionPerformed(evt);
            }
        });

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Voltar.png"))); // NOI18N
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caixaNF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAlterarMed, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoConsultarItens, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoVoltar)
                    .addComponent(caixaNF))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAlterarMed, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsultarItens, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAlterarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarMedActionPerformed
        // TODO add your handling code here:
        if (tabelaNotaFiscal.getSelectedRow() != -1) {
            int cancelarNf = JOptionPane.showConfirmDialog(null, "Cancelar nota fiscal?","CANCELAR NF",JOptionPane.YES_NO_OPTION);
            if (cancelarNf == 0) {
                NotaFiscalDAO nfdao = new NotaFiscalDAO();
                NotaFiscal nf = model.pegaDadosLinha(tabelaNotaFiscal.getSelectedRow());
                nfdao.cancelarI(nf);
                model.recarregaTabela();
            }            
        } 
    }//GEN-LAST:event_botaoAlterarMedActionPerformed

    // CORRIGIR********************************************************************************
    
    private void botaoConsultarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarItensActionPerformed
        // TODO add your handling code here:
        if (tabelaNotaFiscal.getSelectedRow() != -1) {
            NotaFiscal nf = model.pegaDadosLinha(tabelaNotaFiscal.getSelectedRow());
        
            JanelaMedNotaFiscal itensNf = new JanelaMedNotaFiscal(nf, this);
            itensNf.setVisible(true);
        }
    }//GEN-LAST:event_botaoConsultarItensActionPerformed

    private void botaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseClicked
        // TODO add your handling code here:
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarMouseClicked

    private void botaoVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_botaoVoltarMouseEntered

    private void botaoVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_botaoVoltarMouseExited

    private void tabelaNotaFiscalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaNotaFiscalMouseClicked
        // TODO add your handling code here:
        if (tabelaNotaFiscal.getSelectedRow() != -1 && clique != tabelaNotaFiscal.getSelectedRow()) {
            clique = tabelaNotaFiscal.getSelectedRow();
        } else if (tabelaNotaFiscal.getSelectedRow() != -1 && clique == tabelaNotaFiscal.getSelectedRow()){
            clique = -1;
            tabelaNotaFiscal.clearSelection();
        }
    }//GEN-LAST:event_tabelaNotaFiscalMouseClicked

    private String getDateTime() {
	DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
	Date date = new Date();
	return dateFormat.format(date);
    }
    
    public String desconverterData(String dataDigitada){
        String dataFormatada = null;
        
        SimpleDateFormat formatoBanco = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat formatoDesejado = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            Date dataBanco = new Date(formatoBanco.parse(dataDigitada).getTime());
            dataFormatada = formatoDesejado.format(dataBanco);
        } catch (ParseException e) {
        }
        return dataFormatada;
    }
    
    public void formatar(){
        JTableHeader tituloTabela = tabelaNotaFiscal.getTableHeader();
        tituloTabela.setFont(new Font("century gothic", Font.BOLD, 12));
        
        DefaultTableCellRenderer centralizar = (DefaultTableCellRenderer)
                tituloTabela.getDefaultRenderer();
        centralizar.setHorizontalAlignment(JLabel.CENTER);
        centralizar.setVerticalAlignment(JLabel.CENTER);
        
        UIManager.put("OptionPane.cancelButtonText", "Cancelar"); 
        UIManager.put("OptionPane.noButtonText", "Não"); 
        UIManager.put("OptionPane.yesButtonText", "Sim");        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaNf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaNf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaNf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaNf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaNf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarMed;
    private javax.swing.JButton botaoConsultarItens;
    private javax.swing.JLabel botaoVoltar;
    private javax.swing.JLabel caixaNF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaNotaFiscal;
    // End of variables declaration//GEN-END:variables
}
