/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.UsuarioDAO;
import Objetos.Usuario;
import java.awt.Cursor;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author michel.matos
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    
    UsuarioDAO userDao = new UsuarioDAO();
    int tipoUser;
    
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        UIManager.put("OptionPane.cancelButtonText", "Cancelar"); 
        UIManager.put("OptionPane.noButtonText", "Não"); 
        UIManager.put("OptionPane.yesButtonText", "Sim");
    }
    
    public TelaInicial(String codUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        UIManager.put("OptionPane.cancelButtonText", "Cancelar"); 
        UIManager.put("OptionPane.noButtonText", "Não"); 
        UIManager.put("OptionPane.yesButtonText", "Sim");
        
        List<Usuario> user = userDao.pesquisarCod(codUsuario);    
        tipoUser = user.get(0).getTipousuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        genUser = new javax.swing.JButton();
        genDrog = new javax.swing.JButton();
        genVen = new javax.swing.JButton();
        genCom = new javax.swing.JButton();
        imgComp = new javax.swing.JLabel();
        imgVend = new javax.swing.JLabel();
        imgDrog = new javax.swing.JLabel();
        imgUser = new javax.swing.JLabel();
        imgForn = new javax.swing.JLabel();
        genForn = new javax.swing.JButton();
        imgMed = new javax.swing.JLabel();
        genMed = new javax.swing.JButton();
        genNf = new javax.swing.JButton();
        imgNf = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        imgLogout = new javax.swing.JLabel();
        caixaLogin = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 550));

        jLabel3.setText("\n");

        genUser.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        genUser.setText("USUÁRIO");
        genUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genUserActionPerformed(evt);
            }
        });

        genDrog.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        genDrog.setText("DROGARIA");
        genDrog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genDrogActionPerformed(evt);
            }
        });

        genVen.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        genVen.setText("VENDA");
        genVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genVenActionPerformed(evt);
            }
        });

        genCom.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        genCom.setText("COMPRA");
        genCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genComActionPerformed(evt);
            }
        });

        imgComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Compra.png"))); // NOI18N

        imgVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Venda.png"))); // NOI18N

        imgDrog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Drogaria.png"))); // NOI18N

        imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Usuarios.png"))); // NOI18N

        imgForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Fornecedor.png"))); // NOI18N

        genForn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        genForn.setText("FORNECEDOR");
        genForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genFornActionPerformed(evt);
            }
        });

        imgMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Medicamento.png"))); // NOI18N

        genMed.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        genMed.setText("MEDICAMENTO");
        genMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genMedActionPerformed(evt);
            }
        });

        genNf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        genNf.setText("NOTA FISCAL");
        genNf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genNfActionPerformed(evt);
            }
        });

        imgNf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/NotaFiscal.png"))); // NOI18N

        botaoSair.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botaoSair.setText("SAIR");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        imgLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Logout.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(genCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(imgComp))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(imgMed)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genNf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genVen, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(imgVend))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(imgNf)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(genDrog, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgDrog)
                                .addGap(24, 24, 24))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(genUser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(imgUser))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(imgForn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(genForn, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(imgLogout)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(imgVend))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genVen)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgComp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genCom))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgDrog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genDrog))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgForn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genForn)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgMed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genMed))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgNf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genNf))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgUser)
                            .addComponent(imgLogout))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genUser)
                            .addComponent(botaoSair))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        caixaLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        caixaLogin.setText("TELA INICIAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caixaLogin)
                        .addGap(521, 521, 521)))
                .addGap(120, 120, 120)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 90, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(494, 494, 494))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(caixaLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genComActionPerformed
        // TODO add your handling code here:
        JanelaCompra compra = new JanelaCompra(this);
        compra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_genComActionPerformed

    private void genVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genVenActionPerformed
        // TODO add your handling code here:
        JanelaVenda ven;
        try {
            ven = new JanelaVenda(this);
            ven.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_genVenActionPerformed

    private void genDrogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genDrogActionPerformed
        // TODO add your handling code here:
        JanelaDrogaria drogaria;
        try {
            drogaria = new JanelaDrogaria(this);
            drogaria.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_genDrogActionPerformed

    private void genFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genFornActionPerformed
        // TODO add your handling code here:
        JanelaFornecedor fornecedor;
        try {
            fornecedor = new JanelaFornecedor(this);
            fornecedor.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_genFornActionPerformed

    private void genMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genMedActionPerformed
        // TODO add your handling code here:
        JanelaMedicamento medicamento = new JanelaMedicamento(this);
        medicamento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_genMedActionPerformed

    private void genNfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genNfActionPerformed
        // TODO add your handling code here:
        JanelaNf notafiscal = new JanelaNf(this);
        notafiscal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_genNfActionPerformed

    private void genUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genUserActionPerformed
        // TODO add your handling code here:
        if (tipoUser == 1) {
            JanelaUsuario user;
            try {
                user = new JanelaUsuario(this);
                user.setVisible(true);
                this.setVisible(false);
            } catch (ParseException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Apenas usuário administrador");
        }
    }//GEN-LAST:event_genUserActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        int voltar = JOptionPane.showConfirmDialog(null, "Você deseja deslogar?", "Alerta", JOptionPane.YES_NO_OPTION);
        
        if (voltar == 0) {
            this.dispose();
        
            TelaLogin login = new TelaLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel caixaLogin;
    private javax.swing.JButton genCom;
    private javax.swing.JButton genDrog;
    private javax.swing.JButton genForn;
    private javax.swing.JButton genMed;
    private javax.swing.JButton genNf;
    private javax.swing.JButton genUser;
    private javax.swing.JButton genVen;
    private javax.swing.JLabel imgComp;
    private javax.swing.JLabel imgDrog;
    private javax.swing.JLabel imgForn;
    private javax.swing.JLabel imgLogout;
    private javax.swing.JLabel imgMed;
    private javax.swing.JLabel imgNf;
    private javax.swing.JLabel imgUser;
    private javax.swing.JLabel imgVend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
